apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-express
    labels:
        app: mongo-espress
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo-express
        template:
            metadata:
                labels:
                    app: mongo-express
            spec:
                containers:
                    - name: mongo-express
                      image: mongo-express
                      ports:
                          - containerPort: 8081
                      env:
                          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: mongodb-secret
                                    key: mongo-root-username
                          - name: ME-CONFIG_MONGODB_ADMINPASSWORD
                            valueFrom:
                                secretKeyRef:
                                name: mongo-root-password
                                key: mongo-root-password
                          - name: ME_CONFIG_MONGODB-SERVER
                            valueFrom:
                                configMapKeyRef:
                                    name: mongodb-configmap
                                    key: database_url

---
apiVersion: v1
kind: Service
metadata:
    name: mongodb-service
spec:
    selector:
        app: mongodb
    type: LoadBalancer
    ports:
        - protocal: TCP
          port: 8081
          targetPort: 8081
          nodePort: 30000