

GET {{uri}}/


### main
GET {{uri}}
Content-Type: application/json


### all users

GET {{uri}}/users
Content-Type: application/json



# make post request to http://localhost:8000/users with Content-Type: application/json

