indent_style = "Block"
reorder_imports = true
control_brace_style = "ClosingNextLine"
max_width = 80
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
imports_layout = "Vertical"
merge_imports = true